constants:
  file:
    directory: D:\SQL(04-14~)\backend\springboot\upload
  kakao-login:
    token-uri: https://kauth.kakao.com
    user-uri: https://kapi.kakao.com
    redirect-uri: http://localhost:8080/api/v1/account/login/kakao
    app-key: bc1094840538736df46235314177d0b3
  naver-login:
    token-uri: https://nid.naver.com/oauth2.0/token
    user-uri: https://openapi.naver.com/v1/nid/me
    redirect-uri: http://localhost:8080/api/v1/account/login/naver
    app-key: v9mW1kiC_wKvBqxqT9Jo
    secret-key: NzS4_bvtOR
  kakao-pay:
    token-uri: https://open-api.kakaopay.com/online/v1/payment/ready
    secret-key: DEV82F87B8EECEEF87CB48A2F6E3E401272F06EB

spring:
  application:
    name: gallery
  datasource:
    url: jdbc:mariadb://localhost/gallery
    username: root
    password: green502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml