constants:
  file:
    directory: D:\SQL(04-14~)\backend\springboot\upload
  kakao-login:
    url: https://kauth.kakao.com/oauth/token
    app-key: bc1094840538736df46235314177d0b3

spring:
  application:
    name: gallery
  datasource:
    url: jdbc:mariadb://localhost/gallery
    username: root
    password: green502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml